"""empty message

Revision ID: 397610e062f7
Revises: 
Create Date: 2018-03-14 03:49:04.004248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '397610e062f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('posted_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'posted_date')
    # ### end Alembic commands ###
